import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Provider from "@/lib/providers/TanstackProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "100", "200", "800", "900"],
});

// export const runtime = "edge";
export const metadata: Metadata = {
  metadataBase: new URL("https://www.explosionproofelectrical.com"),
  keywords: [
    "Flameproof, Flameproof near me",
    "Flameproof Gujarat",
    "Junction Box",
    "Explosion Proof",
    "Panels",
    "Flameproof Panels",
    "Flameproof Junction boxes",
    "ExEC",
    "Flameproof junction boxes",
    "Flameproof panels",
    "LED fittings",
    "Bulkhead lights",
    "WellGlass fittings",
    "Instrumentation solutions",
    "Switch gears",
    "Clean room fittings",
    "Reactor vessel lamps",
    "Push buttons and switches",
    "Industrial plug tops",
    "Floodlights for hazardous areas",
    "Explosion-proof exhaust fans",
    "Pedestal and wall-mounted fans",
    "Limit switches for industrial use",
    "Hand lamps for hazardous environments",
    "Proximity switches",
    "RPM controllers",
    "Temperature controllers",
    "DOL starters for industrial applications",
    "Explosion-proof electrical control",
    "Flameproof manufacturer in Vapi",
    "Flameproof JBS",
    "Flameproof lighting fixtures",
    "Instrumentation equipment Vapi",
    "Switch gears Vapi",
    "Clean room fittings India",
    "LED light fittings Vapi",
    "WellGlass supplier Gujarat",
    "Bulkhead lights manufacturer",
    "Reactor vessel lamps supplier",
    "Push buttons and switch sockets",
    "Industrial plug tops Vapi",
    "Flood lights for hazardous areas",
    "Explosion-proof exhaust fans India",
    "Pedestal fans manufacturer Gujarat",
    "Wall fans supplier Vapi",
    "Limit switches for industrial use",
    "Hand lamps for hazardous environments",
    "Proximity switches supplier",
    "RPM controller supplier Gujarat",
    "Temperature controller manufacturer",
    "DOL starter supplier Vapi",
    "Electrical control solutions",
    "Industrial lighting fixtures",
    "Flameproof electrical products",
    "Explosion-proof electrical components",
    "Hazardous area lighting solutions",
    "Industrial automation equipment",
    "Electrical safety solutions",
    "ATEX-certified electrical products",
    "ATEX-compliant electrical equipment",
    "Hazardous location lighting",
    "Industrial electrical enclosures",
    "Safety switches for hazardous environments",
    "Explosion-proof control panels",
    "ATEX-approved electrical components",
    "Flameproof cable glands",
    "Industrial electrical fittings",
    "Flameproof electrical enclosures",
    "Explosion-proof LED fixtures",
    "ATEX-rated electrical equipment",
    "Hazardous area electrical solutions",
  ],
  title: {
    default: "Explosion Proof Electrical Control",
    template: "%s | ExEC",
  },
  openGraph: {
    description:
      "Explosion Proof Electrical Control is a leading manufacturer of flameproof electrical solutions located in Vapi, Gujarat, India. We specialize in producing a diverse range of products including flameproof junction boxes, panels, LED fittings, wellGlass, bulkheads, and instrumentation. Our offerings also include switch gears, clean room fittings, reactor vessel lamps, push buttons, and various industrial-grade electrical components. Serving customers in Vapi, Silvassa, Daman, Valsad, and surrounding areas, we provide high-quality, explosion-proof solutions designed for safety and reliability in hazardous environments.",
  },
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg")}>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
